import React from "react";
import Header from "../HousDeckWebsiteComponents/Header";
import Footer from "../HousDeckWebsiteComponents/Footer";
import { Box } from "@mui/system";
import { Typography } from "@mui/material";
import { useMediaQuery } from "@mui/material";

function Content({ width, padding, variant }) {
    const commonProps = [{ name: "Home Services", url: "/home-services" }];
    return (
        <div>
            <Header commonProps={commonProps} />
            <Box
                sx={{
                    textAlign: "start",
                    width: width,
                    margin: "100px auto",
                    padding: padding,
                    wordWrap: 'break-word'
                }}
            >
                <Typography variant={variant} sx={{ fontWeight: "600", color: "#1b685f" }}>
                    HouseDeck Partners - Terms of Use
                </Typography>
                <Box sx={{ color: "#95b2af" }}>
                    <Typography sx={{ mt: 6, fontSize: "16px" }}>
                        We are delighted that you are interested in becoming an Housedeck
                        Partner!
                        <br />
                        <br />
                        These Terms of Use (“Terms”) set forth the conditions to become a
                        partner with Housedeck and use of the Services (defined below) of
                        our website housedecklite.com or mobile application Housedeck
                        (“Platform”) operated and managed by Housedeck Furnishing Private
                        Limited (“Company”), a company duly registered and incorporated
                        under the Companies Act, 2013 and having its re registered office at
                        NO.1, T.C. PALLYA SONNATHAMMANAHALLI K.R.PURAM BANGALORE KA 560036
                        IN .
                        <br />
                        <br />
                        For the purpose of the understated terms and conditions, wherever
                        the context so requires “We/we” or “Our/our” or “Us/us” or
                        “housedecklite.com” or “Housedeck” refers to the Company and shall
                        include its successors and assignees.
                        <br />
                        <br />
                        You/you” or “Your/your” or “Yourself/yourself or Housedeck Partner”
                        shall mean any user interested in registering as a service provider
                        and availing Services on our Platform or his/her representative and
                        any other Person who has agreed to become a subscriber on the
                        Platform by providing information on the Platform or accessing our
                        Platform.
                    </Typography>
                    <Typography
                        sx={{
                            mt: 4,
                            fontWeight: "600",
                            color: "#1b685f",
                            fontSize: "16px",
                        }}
                    >
                        ACCEPTANCE OF TERMS
                    </Typography>
                    <Typography sx={{ mt: 6, fontSize: "16px" }}>
                        PLEASE READ THE PRIVACY POLICY THOROUGHLY AND CAREFULLY BEFORE
                        REGISTERING ON THE PLATFORM.
                        <br />
                        <br />
                        These Terms of Use is an electronic record in terms of Information
                        Technology Act, 2000 and rules thereunder as applicable and the
                        provisions pertaining to electronic records in various statutes as
                        amended by the Information Technology Act, 2000. This electronic
                        record is generated by a computer system and does not require any
                        physical or digital signatures.
                        <br />
                        <br />
                        By visiting our Platform and accessing the information, resources,
                        Services, products, and tools we provide, you understand and agree
                        to UNCONDITIONALLY accept and adhere to the following terms and
                        conditions as stated in this policy (hereafter referred to as ‘Terms
                        of Use’), along with the terms and conditions as stated in our
                        Privacy Policy or any other applicable policy that have been
                        displayed on the Platform. If you do not accept the Terms of Use,
                        you should not use the Platform in any manner and discontinue use of
                        the Service immediately.
                        <br />
                        <br />
                        Further the Company shall have the right, at its sole discretion, to
                        unilaterally modify or change these Terms of Use from time to time
                        without prior notice. You hereby acknowledge and accept that it is
                        your obligation to read the updated Terms of Use periodically to
                        acquaint yourself with any modifications. Your continued use of our
                        Platform after such modifications will constitute a binding
                        agreement of acceptance of the modified terms and conditions.
                    </Typography>
                    <Typography
                        sx={{
                            mt: 4,
                            fontWeight: "600",
                            color: "#1b685f",
                            fontSize: "16px",
                        }}
                    >
                        ELIGIBILITY TO USE THE PLATFORM
                    </Typography>
                    <Typography sx={{ mt: 6, fontSize: "16px" }}>
                        Use of the Platform and Services is limited to parties who can
                        lawfully enter into and form contracts under the Applicable Law. To
                        register with the Platform, the Housedeck Partner must provide its
                        legal name, address, phone number, e-mail address, PAN and GST
                        details, as may be applicable.
                        <br />
                        <br />
                        Any Person who is not competent to enter into a legally binding
                        contract including minors, un- discharged insolvents, Persons of
                        unsound mind etc. are not eligible to use the Platform. Kindly note,
                        the Platform is intended for individuals who are 18 years of age or
                        above.
                        <br />
                        <br />
                    </Typography>
                    <Typography
                        sx={{
                            mt: 4,
                            fontWeight: "600",
                            color: "#1b685f",
                            fontSize: "16px",
                        }}
                    >
                        1.DEFINITIONS
                    </Typography>
                    <Typography sx={{ mt: 6, fontSize: "16px" }}>
                        In this Agreement, unless the context otherwise requires:
                        <br />
                        <br />
                        1.1 “Applicable Law” includes all statutes, enactments, acts of
                        legislature or parliament, ordinances, rules, bye-laws, regulations,
                        notifications, guidelines, policies, directions, directives and
                        orders, requirement or other governmental restrictions or any
                        similar form of decision of, or determination by, or any
                        interpretation, policy or administration, having the force of law in
                        India, as in effect or which may come in effect on a future date;
                        <br />
                        <br />
                        1.2 “Brand Name” or “Brand” shall mean “Housedeck” or such other
                        successor or replacement brand name / trade mark / service mark as
                        may be decided by Housedeck.
                        <br />
                        <br />
                        1.3 “Confidential Information” shall mean any and all data,
                        information, and material that Housedeck Partner has access to while
                        using the Platform and whether identified as confidential or
                        proprietary or not and shall without limitation include information
                        that forms part of or relates to the know-how, trade secrets,
                        Intellectual Property Rights, business plan, strategies, operations,
                        employees, suppliers, Customers, end users, vendors, financials, or
                        otherwise of the Company, user ID and password for the Platform.
                        <br />
                        <br />
                        1.4 “Customer(s)” means any end users, whether any Person or entity,
                        that avails or intends to avail any Housedeck Services from You
                        through the Platform.
                        <br />
                        <br />
                        1.5 “Intellectual Property Rights” includes (a) all rights, title,
                        and interest under any statute or under common law including patent
                        rights; copyrights including moral rights; trademarks and any
                        similar rights in respect of intellectual property, anywhere in the
                        world, whether negotiable or not; (b) any licenses, permissions and
                        grants in connection therewith; (c) applications for any of the
                        foregoing and the right to apply for them in any part of the world;
                        (d) right to obtain and hold appropriate registrations in
                        intellectual property and, (e) all extensions and renewals thereof
                        (f) causes of action in the past, present or future, related thereto
                        including the rights to damages and profits, due or accrued, arising
                        out of past, present or future infringements or violations thereof
                        and the right to sue for and recover the same
                        <br />
                        <br />
                        1.6 “Person” means any natural person, limited or unlimited
                        liability company, corporation, partnership (whether limited or
                        unlimited), proprietorship, hindu undivided family, trust, union,
                        association, society, co-operative society, government or any agency
                        or political subdivision thereof or any other entity that may be
                        treated as a person under Applicable Law.
                        <br />
                        <br />
                        1.7 “Platform” shall mean the platform on which the website is
                        hosted, including the related mobile site and mobile application and
                        bearing the Brand name with any top level domain name, that are
                        required to support the market place managed by or on behalf of
                        Company.
                        <br />
                        <br />
                        1.8 “Services” shall have the meaning set forth in Clause 2;
                        <br />
                        <br />
                        1.9 “Housedeck Services” shall mean home improvement and allied
                        services listed and offered on the Platform in accordance with the
                        terms and conditions set out hereunder.
                        <br />
                        <br />
                    </Typography>
                    <Typography
                        sx={{
                            mt: 4,
                            fontWeight: "600",
                            color: "#1b685f",
                            fontSize: "16px",
                        }}
                    >
                        2.THE Housedeck PLATFORM – SERVICES
                    </Typography>
                    <Typography sx={{ mt: 6, fontSize: "16px" }}>
                        Services – The Company shall provide You the access and technical
                        assistance to a technology enabled internet based intermediary
                        Platform that facilitates (a) the Housedeck Partner to offer and
                        deliver, as an independent third party service provider, Housedeck
                        Services to the Customers; (b) determination of pricing for
                        provision of Housedeck Services to Customers; and (c) timely and
                        accurate receipt of payment from Customer and generation of invoices
                        on your behalf, as and when applicable, for the Housedeck Services
                        performed by You.
                    </Typography>
                    <Typography
                        sx={{
                            mt: 4,
                            fontWeight: "600",
                            color: "#1b685f",
                            fontSize: "16px",
                        }}
                    >
                        3.OBLIGATIONS OF Housedeck PARTNER
                    </Typography>
                    <Typography sx={{ mt: 6, fontSize: "16px" }}>
                        Subject to the terms and conditions herein the Housedeck Partner:
                        <br />
                        <br />
                        3.1 shall create an account and register itself on the Platform with
                        accurate details as required on the Platform. It shall be the
                        obligation of the Housedeck Partner to maintain, at all times,
                        complete and updated information, documents and authorisations, as
                        may be applicable, on the Platform.
                        <br />
                        <br />
                        3.2 shall at all times maintain confidentiality of its account and
                        in no event share the user name and password with any third Person
                        to allow access or use the account. You undertake and warrant that
                        You shall not under any circumstances maintain more than one account
                        on the Platform.
                        <br />
                        <br />
                        3.3 shall make himself/herself available on the Housedeck Platform
                        to undertake requests, as and when an order is so placed by a
                        Customer through the Platform, and to provide Housedeck Services to
                        the Customers within the timelines and to the best of his/her
                        abilities. understands that time is of essence of Housedeck Services
                        and that delay in completion will result in imposition of penalty.
                        <br />
                        <br />
                        3.4 shall incur all expenses, including cost of all raw materials,
                        required for performance of Housedeck Services, unless otherwise
                        agreed by the Company.
                        <br />
                        <br />
                        3.5 shall comply with and procure all its
                        helpers/employees/assistants shall comply with personal health
                        regulations and shall at all times wear gloves, masks and Company
                        authorized uniform during the performance of Housedeck Services.
                        <br />
                        <br />
                        3.6 shall not under any circumstances deviate from the quality
                        guidelines specified by the Company.
                        <br />
                        <br />
                        3.7 shall ensure proper clean-up of the Customers’ premises after
                        completion of work; remove and recycle all packaging materials,
                        shrink wrap, used and waste material, unless otherwise instructed by
                        Company or the customers.
                        <br />
                        <br />
                        3.8 undertakes that any and all Confidential Information accessed as
                        result of use of Services shall not be disclosed to any third
                        Person. Under no circumstances the Housedeck Partner shall use
                        Customer’s personal data/information, for any reason, other than for
                        the purpose of fulfilling Housedeck Services, as per these Terms of
                        Use.
                        <br />
                        <br />
                        3.9 shall ensure that all services are delivered to the Customer by
                        properly trained professionals suited for such services provided to
                        the Customer. The Housedeck Partner its helpers/employees/assistants
                        shall maintain highest professional integrity, diligence and care
                        while delivering such services.
                    </Typography>

                    {/* 3.9 tak ho gya agle 4 se start krna h baad me */}

                </Box>
            </Box>
            <Footer />
        </div>
    );
}

export default function HouseDeckHomeServicesTC() {
    const xlMax = useMediaQuery("(max-width:2000px)");
    const xlMin = useMediaQuery("(min-width:1200px)");
    const mdMax = useMediaQuery("(max-width:1200px)");
    const mdMin = useMediaQuery("(min-width:600px)");
    const sm = useMediaQuery("(max-width:600px)");
    return (
        <>
            {xlMax && xlMin && <Content width={"1170px"} padding={"unset"} variant={'h3'} />}
            {!(xlMax && xlMin) && mdMax && mdMin && (
                <Content width={"unset"} padding={"0px 70px"} variant={'h3'} />
            )}
            {sm && <Content width={"unset"} padding={"0px 20px"} variant={'h5'} />}
        </>
    );
}
